### ISSUE TITLE
Update to v1.2.6.14

### ISSUE THREAD

**Issue by serial77** [ny0c/profittrailer-crack#3]
@ny0c 
Can you please do a quick update to the latest official build?

Expect a nice donation ;)

**Comment by aries-delossantos** [comment]
Also waiting for this. Will definitely send donation. :) thanks1

**Comment by ny0c** [comment]
Updated

**Comment by aries-delossantos** [comment]
Still the same version on the footer. 
`PT Ver:  1.2.6.11`

**Comment by serial77** [comment]
@aries-delossantos I see  P T Ver: 1.2.6.14 on footer after update. Shut your bot down, replace only the .jar file with latest version, reboot machine, start bot.
